M48
; DRILL file {KiCad 7.0.5} date Fri Sep  1 16:08:52 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-01T16:08:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.8228Y-3.8238
T2
X4.0354Y-3.8238
T0
M30
