M48
; DRILL file {KiCad 7.0.5} date Mon Aug 28 16:59:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-28T16:59:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0709
%
G90
G05
T1
X4.1968Y-4.2953
X4.1968Y-4.5232
T2
X4.8228Y-3.8238
T3
X4.3482Y-4.9272
X4.3482Y-5.124
T4
X4.0354Y-3.8238
T0
M30
